name: GDM Check and Conversion
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: GDM Secrets
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7' # Not needed with a .ruby-version file
    - 
      name: Install Gems
      run: gem install dropbox-deployment mdl
    - 
      name: Check Syntax
      run: sh check_readme.sh
    - 
      name: Convert to CSV/YAML
      run: ruby converter.rb
    - 
      name: Convert to Sequel Schema
      run: ruby convert_to_schema.rb
    - 
      name: Prepare schemas archive
      run: (cd artifacts && tar jcvf gdm_schemas.tbz schemas)
    - 
      name: Upload to Dropbox
      run: dropbox-deployment